### ISSUE TITLE
Code depends on `Mix.env` being present, which it won't be in production

### ISSUE THREAD

**Issue by Trevoke** [jbernardo95/cronex#4]
```
    ** (EXIT) shutdown: failed to start child: Cronex.Table
        ** (EXIT) an exception was raised:
            ** (UndefinedFunctionError) function Mix.env/0 is undefined (module Mix is not available)
                Mix.env()
                (cronex) lib/cronex/table.ex:108: Cronex.Table.ping_interval/0
                (cronex) lib/cronex/table.ex:104: Cronex.Table.new_ping_timer/0
                (cronex) lib/cronex/table.ex:48: Cronex.Table.init/1
                (stdlib) gen_server.erl:328: :gen_server.init_it/6
                (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

Just deployed Cronex in prod and killed my server because of this error.

Seems to be this line of code:

https://github.com/jbernardo95/cronex/blob/master/lib/cronex/table.ex#L104

So obviously your library is unusable right now, unfortunately. I'd make this an env-level variable if I were you, configurable by the user, with a sane default.

**Comment by jbernardo95** [comment]
Resolved here 54db3840708c0f82929675f4115312c4e2b4f363.

Will be out in the next release, use master for now if you need it.
